### ISSUE TITLE
A "syntax error" on OS X

### ISSUE THREAD

**Issue by psprint** [MichaelAquilina/zsh-auto-notify#1]
Hello,
after running `sleep 11` I'm getting:
```
22:28: syntax error: Element „identyfikator” nie może następować po „„"””. (-2740)
```
which translated to English is:
```
22:28: syntax error: Element „identificator” cannot occur after „„"””. (-2740)
```

**Comment by MichaelAquilina** [comment]
So I'm afraid I dont have access to a Mac machine to test this which is why it is broken. Would you like to attempt a PR yourself to see if you can fix it? I can point you to the exact line which is broken: https://github.com/MichaelAquilina/zsh-auto-notify/blob/master/auto-notify.plugin.zsh#L27

**Comment by psprint** [comment]
Glad that it's fixed :)
