### ISSUE TITLE
Notifications is send again when doing Ctrl+C

### ISSUE THREAD

**Issue by onde2rock** [MichaelAquilina/zsh-auto-notify#13]
# Issue Details
When I do Ctrl+C on the command line after a command that triggered a notification, the notification is sent again.

## Operating System (uname -a)

rhel

## zsh version (zsh --version)
zsh 5.7.1 (x86_64-pc-linux-gnu)

## auto-notify version (echo "$AUTO_NOTIFY_VERSION")
0.1.0
## How is auto-notify installed?

manually

## Steps to reproduce the issue

Run a long running command. When it exit, a notification is send.
Do Ctrl+C => the notification is send again.
Do Ctrl+C => the notification is send again.
Do Ctrl+C => the notification is send again.

## gist link to your zshrc

Gmrl config => https://git.grml.org/?p=grml-etc-core.git;a=blob_plain;f=etc/zsh/zshrc;hb=HEAD

**Comment by MichaelAquilina** [comment]
@onde2rock this is fixed in the latest release. Please upgrade to latest by git pulling (seeing as its installed manually).

You can tell if the plugin has been updated when the versions shows

**Comment by onde2rock** [comment]
Yes, the last version fixed it. Thanks
