### ISSUE TITLE
Add option oppsite to AUTO_NOTIFY_IGNORE

### ISSUE THREAD

**Issue by webhive** [MichaelAquilina/zsh-auto-notify#20]
# Issue Details

This plugin is helpful for me, but with my workflow I need it only for certain commands, but not to each one. So current behaviour is pretty annoying. Add commands to AUTO_NOTIFY_IGNORE seems an overhead as I adding more and more there. So it could be great to have some option to use this plugin to subset of allowed commands which are really need my attention instead of flood me with tons of notices.

## Operating System (uname -a)

Linux 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux

## zsh version (zsh --version)

zsh 5.7.1 (x86_64-pc-linux-gnu)

## auto-notify version (echo "$AUTO_NOTIFY_VERSION")

0.4.0

## How is auto-notify installed?

- [x] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

**Comment by MichaelAquilina** [comment]
It's a good suggestion. Right now `AUTO_NOTIFY_IGNORE` is basically a blacklist. What you are suggesting is basically asking for an explict whitelist instead. Should be pretty easy to implement. Would you like to try giving this a go yourself? Happy to do it myself otherwise

**Comment by MichaelAquilina** [comment]
@webhive please see if #21 solves your issue

**Comment by webhive** [comment]
Briefly tested - seems work

**Comment by MichaelAquilina** [comment]
Merged into master. Hope that helps you with your issue :)
