### ISSUE TITLE
Timeout ignored when urgency level critical

### ISSUE THREAD

**Issue by yoyo-san** [MichaelAquilina/zsh-auto-notify#26]
Hi,
I noticed that once the command finishes with non-zero exit code the plugin will set urgency level to _critical_. It appears that on some systems underlying library ignores the timeout (`--expire-time`). I noticed this on KDE5, but read some reports about GNOME and Ubuntu. 
I plan to move to Dunst soon, but anyway. 
Please note that it's not zsh-auto-notify bug, but it would be great to make a workaround.
Would it be possible to add another variable to skip this behavior? I can make a PR.

## Operating System (uname -a)
Arch Linux 5.2.14-arch2-1-ARCH

## zsh version (zsh --version)
zsh 5.7.1 (x86_64-pc-linux-gnu)

## auto-notify version (echo "$AUTO_NOTIFY_VERSION")
0.7.0
## How is auto-notify installed?
zgen
## Steps to reproduce the issue
Use zsh-auto-notify on KDE (perhaps also GNOME3 or Ubuntu).

**Comment by Avi-D-coder** [comment]
The fix is https://github.com/MichaelAquilina/zsh-auto-notify/pull/24

**Comment by yoyo-san** [comment]
Sorry, didn't see it. Thanks!
