### ISSUE TITLE
Is it possible to get this work when working via ssh?

### ISSUE THREAD

**Issue by grst** [MichaelAquilina/zsh-auto-notify#29]
Hi @MichaelAquilina, 

great tool! 
It works perfectly when running in a local terminal, but not when working via SSH on a remote machine. 

I don't know how the notification system works... do you think it would be possible to get this to run also when inside SSH? 

Cheers,
Gregor

**Comment by MichaelAquilina** [comment]
Hi Gregor,

Unfortunately due the way SSH works that would be impossible. You are effectively working on another machine which has no access to your notification service as well as having its own bash/zsh setup.

Hope that answers your question for you!

**Comment by grst** [comment]
Thanks, I was already suspecting that.

**Comment by ronan-nexthop** [comment]
works with OSC99, I have it working
