### ISSUE TITLE
Some options cannot be set in .zshenv

### ISSUE THREAD

**Issue by jeffmhubbard** [MichaelAquilina/zsh-auto-notify#30]
# Issue Details

I tried setting `AUTO_NOTIFY_THRESHOLD` and `AUTO_NOTIFY_WHITELIST` in my `.zshenv`. The whitelist works fine, but threshold doesn't. `.zshenv` gets sourced before `.zshrc`, so when the plugin is loaded it overwrites `AUTO_NOTIFY_THRESHOLD` with the default (also `AUTO_NOTIFY_EXPIRE_TIME` and `AUTO_NOTIFY_IGNORE`).

Couldn't/shouldn't these have a corresponding `DEFAULT_` instead of being exported? Or at least check that the variable isn't already set.

## Operating System (uname -a)
`Linux pythos 5.5.1-arch1-1 #1 SMP PREEMPT Sat, 01 Feb 2020 16:38:40 +0000 x86_64 GNU/Linux`
## zsh version (zsh --version)
`zsh 5.7.1 (x86_64-pc-linux-gnu)`
## auto-notify version (echo "$AUTO_NOTIFY_VERSION")
`0.8.0`
## How is auto-notify installed?

- [ ] zplug
- [ x] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

```sh
% cat .zshenv|grep AUTO_NOTIFY_THRESHOLD
export AUTO_NOTIFY_THRESHOLD=60
% source .zshenv
% echo $AUTO_NOTIFY_THRESHOLD
60
% exec zsh
% echo $AUTO_NOTIFY_THRESHOLD
10
```

**Comment by MichaelAquilina** [comment]
You are right - the order of where you export these options should ideally not make a difference. The fix is relatively easy so I'll add that when I get the chance

**Comment by jeffmhubbard** [comment]
I've learned I was using `.zshenv` all wrong and have moved everything back to `.zsrhc`. So, not much of an issue anymore.
