### ISSUE TITLE
Unknown option --transient

### ISSUE THREAD

**Issue by engeir** [MichaelAquilina/zsh-auto-notify#46]
# Issue Details

Some long running commands get a notification as expected, while others (running and finishing `nvim` typically get this error) do not get a notification, but instead a warning message is printed:

```bash
$ nvim
Unknown option --transient
```

I suppose it is related to [these lines](https://github.com/MichaelAquilina/zsh-auto-notify/blob/dad1e61c71af047e8f07c40b00611a31290be533/auto-notify.plugin.zsh#L53-L60).

## Operating System (uname -a)

```bash
Linux ubuntu-work 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

## zsh version (zsh --version)

```bash
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
```

## auto-notify version (echo "$AUTO_NOTIFY_VERSION")

```bash
0.8.0
```

## How is auto-notify installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x] Other (please specify)

Installed with [zap](https://github.com/zap-zsh/zap).

## Steps to reproduce the issue

With zap, installation is done as: [link to location in zshrc](https://github.com/engeir/stowfiles/blob/688a7bead9883f8fa2dbca10b6d4784ed7ce01d5/zsh_mac/.config/zsh/.zshrc#L20)

```zsh
# .zshrc
...
plug "MichaelAquilina/zsh-auto-notify"
...
```

## gist link to your zshrc

zshrc files are form the `zsh_mac` directory (also my when on my linux machine): [zsh_mac](https://github.com/engeir/stowfiles/tree/main/zsh_mac).

**Comment by engeir** [comment]
I'm on

```console
$ notify-send --version
notify-send 0.7.9
```

**Comment by MichaelAquilina** [comment]
@Grafcube as the author of the original PR, could you confirm `--hint=int:transient:1` works for you?

**Comment by Grafcube** [comment]
> @Grafcube as the author of the original PR, could you confirm `--hint=int:transient:1` works for you?
> 
> I can confirm that it seems to work for me on `notify-send` 0.8.2

I can confirm that `--hint=int:transient:1` works for me on notify-send 0.8.2.

**Comment by MichaelAquilina** [comment]
Please try out the latest release and let me know if it works for you :)
