### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [MichaelAquilina/zsh-auto-notify#5]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by MichaelAquilina** [comment]
My bad @unixorn, forgot to add that in. Will fix :)

**Comment by MichaelAquilina** [comment]
Fixed on latest master

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/739, thanks!
