### ISSUE TITLE
Invalid number of options when no icon is set

### ISSUE THREAD

**Issue by Grelo4ka** [MichaelAquilina/zsh-auto-notify#59]
# Issue Details
zsh-auto-notify results with `Invalid number of options.` error when no icon is set. The [problematic line](https://github.com/MichaelAquilina/zsh-auto-notify/blob/452eee9454289c8a0a7269eeb1870c842685703d/auto-notify.plugin.zsh#L67C9-L67C137) is: 
`notify-send "$title" "$body" --app-name=zsh $transient "--urgency=$urgency" "--expire-time=$AUTO_NOTIFY_EXPIRE_TIME" "$icon_arg"`
Removing `$icon_arg` fixes the issue.

## Operating System (uname -a)
`Linux hostname 6.8.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000 x86_64 GNU/Linux`
## zsh version (zsh --version)
`zsh 5.9 (x86_64-pc-linux-gnu)`
## auto-notify version (echo "$AUTO_NOTIFY_VERSION")
`0.10.0`
## How is auto-notify installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x] Other (direct with zsh4humans)

## Steps to reproduce the issue
1. Install zsh
2. Install zsh4humans
3. Install zsh-auto-notify
4. Don't set the icon
5. sleep 11 
## gist link to your zshrc
https://gist.githubusercontent.com/Grelo4ka/d6792dc219b1e285fba49f09a94bff54/raw/2517750c08fc720df06e2c5807c4e44e69eb2bd7/gistfile1.txt

**Comment by Sujiuzii** [comment]
change the line of notify-send to
`notify-send "$title" "$body" --app-name=zsh $transient --urgency=$urgency --expire-time=$AUTO_NOTIFY_EXPIRE_TIME $icon_arg` working for me.

**Comment by Sujiuzii** [comment]
> change the line of notify-send to `notify-send "$title" "$body" --app-name=zsh $transient --urgency=$urgency --expire-time=$AUTO_NOTIFY_EXPIRE_TIME $icon_arg` working for me.

I removed the quotation mark of the options

**Comment by MichaelAquilina** [comment]
Sorry for that, would you be able to check if the latest changes (version 0.10.1) fix your issues?

**Comment by Sujiuzii** [comment]
> Sorry for that, would you be able to check if the latest changes (version 0.10.1) fix your issues?

yes, that works

**Comment by Grelo4ka** [comment]
> Sorry for that, would you be able to check if the latest changes (version 0.10.1) fix your issues?

can confirm it works, thanks!
